// Token jurisdiction policy v2 (EKU-853, CLO 2026-10-06).
//
// jurisdiction-policy/ekubo-token-jurisdictions-v2.json is generated by
// scripts/jurisdiction-policy.ts and vendored byte-for-byte into
// ekubo-mcp-server (src/jurisdiction-policy.json) and the interface
// (src/util/common/jurisdictionPolicy.json). On chain 4663 every address is
// a Robinhood Assets (Jersey) Stock Token (`rhj_stock_token`), verified not to
// be one (`non_class`), or `unknown`, and consumers hold unknown assets. The country lists
// are a minimum product-policy floor, not a legal determination.
import { tokenKey } from "./token-list";
import type { Token } from "./types";

export const JURISDICTION_POLICY_PATH =
  "jurisdiction-policy/ekubo-token-jurisdictions-v2.json";
export const JURISDICTION_POLICY_VERSION = "ekubo-token-jurisdictions-v2";
export const CLASSIFIED_CHAIN_ID = "4663";

export interface Provenance {
  source: string;
  ref: string;
  observed_at: string;
}

export interface PolicyEntry {
  address: string;
  symbol: string;
  provenance: Provenance[];
}

export interface JurisdictionPolicy {
  policy_version: string;
  chains: Record<
    string,
    {
      unknown: "hold";
      non_class: PolicyEntry[];
      rhj_stock_token: PolicyEntry[];
    }
  >;
}

export function classifiedKeys(policy: JurisdictionPolicy): Set<string> {
  const chain = policy.chains[CLASSIFIED_CHAIN_ID];
  if (!chain) throw new Error(`Policy has no chain ${CLASSIFIED_CHAIN_ID}`);
  return new Set(
    [...chain.rhj_stock_token, ...chain.non_class].map((entry) =>
      tokenKey(CLASSIFIED_CHAIN_ID, entry.address),
    ),
  );
}

export function unclassifiedTokens(
  tokens: readonly Token[],
  policy: JurisdictionPolicy,
): Token[] {
  const known = classifiedKeys(policy);
  const chain = BigInt(CLASSIFIED_CHAIN_ID);
  return tokens.filter(
    (token) =>
      BigInt(token.chain_id) === chain &&
      !known.has(tokenKey(token.chain_id, token.token_address)),
  );
}

export function assertClassified(
  tokens: readonly Token[],
  policy: JurisdictionPolicy,
  label: string,
): void {
  if (policy.policy_version !== JURISDICTION_POLICY_VERSION) {
    throw new Error(
      `${JURISDICTION_POLICY_PATH}: expected ${JURISDICTION_POLICY_VERSION}, got ${policy.policy_version}`,
    );
  }
  const unclassified = unclassifiedTokens(tokens, policy);
  if (unclassified.length === 0) return;
  const rows = unclassified
    .map((token) => `${token.token_symbol} ${token.token_address}`)
    .join(", ");
  throw new Error(
    `${label}: unclassified chain-${CLASSIFIED_CHAIN_ID} token; classify under EKU-853 policy before listing: ${rows}`,
  );
}
